name: Build macOS app

on:
  push:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-14
    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Get JUCE and oolib (submodules)
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive --depth 1

      - name: Configure
        run: cmake -B cmake_build -G Xcode

      - name: Build
        run: cmake --build cmake_build --config Release -- -quiet

      - name: Package
        run: |
          cd cmake_build/SquidManager_artefacts/Release
          ditto -c -k --keepParent SquidSingle.app "$GITHUB_WORKSPACE/SquidSingle-mac.zip"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: SquidSingle-mac
          path: SquidSingle-mac.zip
